### ISSUE TITLE
README says "please use Python 2.7"

### ISSUE THREAD

**Issue by pberkes** [ASPP/pelita_player_2015#1]

**Comment by Debilski** [comment]
Updating it is three clicks.

**Comment by pberkes** [comment]
+1

**Comment by Debilski** [comment]
Closed in https://github.com/ASPP/pelita_player_2015/commit/627cc8bdecb7471e8870505941f5c0be0f79180e

**Comment by pberkes** [comment]
No Pull Request? :scream:

**Comment by Debilski** [comment]
`git regret --hard`
